<!--<div id="map" style="width: 800px; height: 600px"> </div>-->
<!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.14.1/css/ol.css" type="text/css">-->
<!--<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.14.1/build/ol.js"></script>-->
<!--    <script type="text/javascript">-->
<!--          var userLat            = 53.511640;-->
<!--          var userLon            = -2.335810;-->
<!--          var userZoom           = 11;-->
<!---->
<!--          var map = new ol.Map({-->
<!--              target: 'map',-->
<!--              layers: [-->
<!--                  new ol.layer.Tile({-->
<!--                      source: new ol.source.OSM()-->
<!--                  })-->
<!--              ],-->
<!--              view: new ol.View({-->
<!--                  center: ol.proj.fromLonLat([ userLon, userLat]),-->
<!--                  zoom: userZoom-->
<!--              })-->
<!--          });-->
<!--        function getLocation(lon, lat) {-->
<!--            fetch('http://nominatim.openstreetmap.org/reverse?format=json&lon=' + lon + '&lat=' + lat).then(function(response) {-->
<!--                return response.json();-->
<!--            }).then(function(json) {-->
<!--                document.getElementById('address').innerHTML = json.display_name;-->
<!--            })-->
<!--        }-->
<!--        map.on('click', function(e) {-->
<!--            var coordinate = ol.proj.toLonLat(e.coordinate).map(function(val) {-->
<!--                return val.toFixed(6);-->
<!--            });-->
<!--            var lon = document.getElementById('lon').value = coordinate[0];-->
<!--            var lat = document.getElementById('lat').value = coordinate[1];-->
<!--            getLocation(lon, lat);-->
<!--        });-->
<!--        document.getElementById('reversegeocoding').addEventListener('click', function(e) {-->
<!--            if (document.getElementById('lon').value && document.getElementById('lat').value) {-->
<!--                getLocation(document.getElementById('lon').value, document.getElementById('lat').value);-->
<!--            }-->
<!--        });-->
<!---->
<!---->
<!--    </script>-->