<?php
/**
 * Lists complete information about the user in a card form
 * @param UserData $userData
 */
function listUserDetails(UserData $userData){
    $element = '

    <div class="col">
       <div class="card m-1 p-1 mt-2"  style="width: 20rem">
            <img class="img-thumbnail" src="'.$userData->getPhoto().'"  class="card-img-top" alt="Friend\'s Photo">
        <div class="card-body">
            <h5 class="card-title">'.$userData->getFirstName().' '.$userData->getLastName().'</h5>
            <h6 class="card-subtitle mb-2 text-muted">'.$userData->getUsername().'</h6>
            <div class="p-2">'.$userData->getEmail().'</div>
            <div class="p-2">'.$userData->getPhoneNumber().'</div>
            <div class="p-2">'.$userData->getLatitude().'</div>
            <div class="p-2">'.$userData->getLongitude().'</div>
            </div>
        <div class="card-footer" style="height: 4em">
            <small class="text-muted">'.displayFriendshipStatus($_SESSION["uid"],$userData->getID()).'</small>
        </div>
       </div>
    </div>';

    echo $element;


}

/**
 * Lists limited information about the users in a card form - used when not logged-in
 * @param $userData - a single line of UserData object
 */
 function listPublicUserDetails(UserData $userData){

     $element = '
    <div class="col">
       <div class="card m-1 p-1 mt-2"  style="width: 20rem">
            <img class="img-thumbnail" src="'.$userData->getPhoto().'"  class="card-img-top" alt="Friend\'s Photo">
        <div class="card-body">
            <h5 class="card-title">'.$userData->getFirstName().' '.$userData->getLastName().'</h5>
            <h6 class="card-subtitle mb-2 text-muted">'.$userData->getUsername().'</h6>
            <div class="p-2">'.$userData->getEmail().'</div>
            </div>
        <div class="card-footer" style="height: 4em">
        </div>
       </div>
    </div>';

     echo $element;

 }

/**
 * Displays different buttons underneath the user data depending on type of friendship
 * */
function displayFriendshipStatus($userID,$friendID)
{
    //Values - 0-not friends 1- pending, 2-accept/deny - 3 -friends
    $temp = new UserDataSet();
    $friendshipStatus = $temp->getFriendshipStatus($userID,$friendID);
    if($friendshipStatus == 0) return '<form  method="post"><button class="btn btn-success" name="changeFriend" value="invite" type="submit">Invite</button><input type="hidden" id="userID" name="userID" value="' .$userID.'"><input type="hidden" id="friendID" name="friendID" value="'.$friendID.'"></form>';
    else if($friendshipStatus == 1) return 'Invitation pending';
    else if($friendshipStatus == 2) return '<form  method="post"><button class="btn btn-success" name="changeFriend" value="accept" type="submit">Accept</button><button class="btn btn-success float-right" name="changeFriend" value="deny" type="submit">Deny<input type="hidden" id="userID" name="userID" value="' .$userID.'"><input type="hidden" id="friendID" name="friendID" value="'.$friendID.'"></form></button>';
    else if($friendshipStatus == 3) return '<form  method="post"><button class="btn btn-danger" name="changeFriend" value="remove" type="submit">Remove Friend<input type="hidden" id="userID" name="userID" value="' .$userID.'"><input type="hidden" id="friendID" name="friendID" value="'.$friendID.'"></form></button>';
    //.displayFriendshipStatus($friendshipStatus) .
}


