<?php
require_once('Views/friendListElement.phtml');


//List all users non-public data
$userDataSet = new UserDataSet();
$usersPerPage = $userDataSet->countUsers();
$resultsPerPage = 10;
$numberOfPages = ceil($usersPerPage / $resultsPerPage);

if(!isset($_GET['page'])){
    $page = 1;
    $_GET['page'] = 1;
}else {
    $page = $_GET['page'];
}

$users = $userDataSet->fetchAllUsers($page, $resultsPerPage );
echo '<div class="card-group">';
if(!isset($_SESSION["login"])){
    foreach($users as $user)
    {
      listPublicUserDetails($user);
    }} else {
    foreach($users as $user)
    {
        listUserDetails($user);
    }
}
echo '</div>';

?>
<!--Pagination-->
<nav class="mw-100" aria-label="pagination">
    <ul class="pagination flex-wrap">
        <?php
        if($_GET['page'] == 1) {
            echo '<li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a></li>';
        }else{
            $previousPage = $_GET['page'] - 1;
            echo '<li class="page-item"><a class="page-link" href="index.php?page='.$previousPage.'">Previous</a></li>';
        }
        for($page = 1 ; $page <= $numberOfPages; $page++) {
            if($page == $_GET['page']){
                echo'<li class="page-item active" aria-current="page"><a class="page-link" href="index.php?page='.$page.'">'.$page.'</a>';
            }else{
                echo '<li class="page-item"><a class="page-link" href="index.php?page='.$page.'">'.$page.'</a></li>';
            }

        }
        if($_GET['page'] == $numberOfPages) {
            echo '<li class="page-item disabled">
                            <a class="page-link" href="#">Next</a></li>';
        }else{
            $previousPage = $_GET['page'] + 1;
            echo '<li class="page-item"><a class="page-link" href="index.php?page='.$previousPage.'">Next</a></li>';
        }?>
    </ul>
</nav>





