<?php require('template/header.phtml') ?>



   <div class="col-xl-3 col-lg-4 col-md-2 col-sm-1 mx-auto"></div>
   <div class="col-xl-1 col-lg-5 col-md-8 col-sm-10 formBox mx-auto">
       <!--login form start-->
       <h3> Login </h3>
       <form class="p-3">
           <div class="form-group">
               <label for="emailInput">Email Address:</label>
               <input type="email" class="form-control" id="emailInput" placeholder="E-mail">
           </div>
           <div class="form-group">
               <label for="passwordInput">Password:</label>
               <input type="password" class="form-control" id="passwordInput" placeholder="Password">
           </div>
           <button type="submit" class="btn btn-primary">Login</button>
           <hr />
           Don't have an account?
           <a href="registration.php" role="button" class="btn btn-link" >Register here</a>
           <a href="passwordreset.php" role="button" class="btn btn-link">Reset Password</a>
           <a href="messenger.php" role="button" class="btn btn-link">Messenger</a>
       </form>
       <!--login form end-->
   </div>
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-1"></div>

<?php require('template/footer.phtml') ?>
