
<!-- Modal for a login box -->
<div class="modal fade" id="popUpLogin" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign-in</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="p-3" method="post"  action="">
                    <div class="form-group" >
                        <label for="loginInput">Login</label>
                        <input type="text"  name="loginInput" class="form-control" id="loginInput" placeholder="Login" aria-label="login">
                    </div>
                    <div class="form-group">
                        <label for="passwordInput">Password:</label>
                        <input type="password" name="passwordInput" class="form-control" id="passwordInput" placeholder="Password" aria-label="password">
                    </div>
                    <div class="p-2"></div>
                    <button type="submit" class="btn btn-success" name="login" id="loginButton" aria-label="loginButton">Login</button>
                    <hr />
                    Don't have an account?
                    <a href="registration.php" role="button" class="btn btn-link" >Register here</a>
                    <a href="passwordreset.php" role="button" class="btn btn-link">Reset Password</a>
                </form>
            </div>
        </div>
    </div>
</div>

