<?php require_once 'template/header.phtml';
require_once './login.php';?>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php"><img class="navbar-left" src="images/logo.transparent.gif" id="Logo" height="50vn" alt="logo" ></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active"  href="selfAssesment.docx">Self-assesment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active"  href="index.php?showAll=true&page=1">Show All Users</a>
                </li>
                <?php if(isset($_SESSION["login"])){
                    echo '

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Friends...
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="index.php?listFriends=true">List Friends</a></li>
                        <li><a class="dropdown-item" href="index.php?map=true"><i class="bi bi-geo-alt"></i> Map of Friends</a></li>
                    </ul>
                </li>';} ?>
                <li class="nav-item px-5">
                    <form class="d-flex" method="get" action="index.php">
                        <div class="input-group position-relative">
                            <input type="text" class="form-control"  name="searchField" type="search" onkeyup="showHint(this.value)" id="findFriends" placeholder="search..." aria-label="Search" aria-describedby="search">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary"type="submit">Search</button>
                            </div>

                        </div>
                    </form></li>
                <!-- Div with suggested results-->
                <li class="nav-item">

                </li>
                <?php
                //Display log in button if not logged in
                if(!isset($_SESSION["login"])) {
                    echo '    
            
                        <li class="nav-item float-right"><a class="nav-link active" href="#" data-bs-toggle="modal" data-bs-target="#popUpLogin">Login</a></li>
                     <li class="nav-item float-right"><a href="index.php?register=true" class="nav-link active">Register</a></li>';
                }
                else {
                    //Display logout button if logged in
                    echo '
                        <li class="nav-item d-flex"><form method="post" action=""><button class="btn btn-light  my02 my-sm-0" 
                                    type="submit" name="logout" id="logoutButton" aria-label="Logout"> Logout</button> </form></li> ';
                }?>

            </ul>


        </div>
    </div>
</nav>

<div class=" ps-5 d-flex bg-light">
    <div class="col-3" id="nameSuggestion"></div>
    <ul class="list-group col-9" style="max-height:20em;overflow:hidden; overflow-y:scroll;" id="userSuggestion"></ul>

</div>
<script>

    function showHint(str) {
        if (str.length == 0) {
            document.getElementById("userSuggestion").innerHTML = "";
            document.getElementById("nameSuggestion").innerHTML = "";

            return;
        } else {
            var data;
            let xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if(this.readyState == 4 && this.status == 200) {
                    data = this.responseText;
                    var userData = JSON.parse(data);
                    var userList ='';
                    userList += '<p>Suggested names:</p>';
                    for (var i = 0; i < userData.length; i++) {
                        var user = userData[i];
                        userList += generateUserSuggestions(user);
                    }
                    var vic = document.getElementById("userSuggestion");
                    vic.innerHTML = userList;
                }
            }
            xmlhttp.open("GET", "ajaxSearch.php?q=" + str);
            xmlhttp.send();

            let xmlrequest = new XMLHttpRequest();
            xmlrequest.onreadystatechange = function() {
                if(this.readyState == 4 && this.status == 200) {
                    var names = JSON.parse(this.responseText);
                    var namesList = '';
                    namesList += '<p>Did you mean:</p>';
                    namesList += '<ul class="list-group col-3 d-flex" style="list-style-type: none" id="nameSuggestion">';
                    var counter = 0;
                    for (var name of names) {
                        console.log(name._firstname);
                        if(name._firstname.includes(str) && counter < 10){
                            namesList += generateNameSuggestions(name);
                            counter++;
                        }
                    };
                    namesList += '</ul>';
                    var namesListHtml = document.getElementById("nameSuggestion");
                    namesListHtml.innerHTML = namesList;
                }
            }
            xmlrequest.open("GET", "names.json");
            xmlrequest.send();


        }
    }

    function generateUserSuggestions(data){
        return '<li class="list-group-item d-flex justify-content-between align-items-center container-f" style=" background-color: white;"> ' +
            '<a class="text-decoration-none text-black" href="index.php?searchField='+ data._firstname +'">' +
            '<span><img class="img-fluid rounded me-3" style="width:40px" src="'+ data._photo +'"></span>' +
            '<span class="ms-1">' + data._firstname + ' '+ data._lastname + '</span>' +
            '</a></li>';
    }

    function generateNameSuggestions(data){
        return '<li><a class=" text-black" href="index.php?searchField='+ data._firstname +'">'+ data._firstname +'</a></li>';
    }
</script>


