<?php require_once 'template/header.phtml';
require_once './login.php';?>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php"><img class="navbar-left" src="images/logo.transparent.gif" id="Logo" height="50vn" alt="logo" ></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active"  href="selfAssesment.docx">Self-assesment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active"  href="index.php?showAll=true&page=1">Show All Users</a>
                </li>
                <?php if(isset($_SESSION["login"])){
                    echo '

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Friends...
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Invite/accept friends</a></li>
                        <li><a class="dropdown-item" href="index.php?listFriends=true">List Friends</a></li>
                        <li><a class="dropdown-item" href="index.php?map=true"><i class="bi bi-geo-alt"></i> Map of Friends</a></li>
                    </ul>
                </li>';} ?>
                <li class="nav-item px-5">
                    <form class="d-flex" method="post" action="index.php">
                        <div class="input-group">
                            <input type="text" class="form-control" name="searchField" type="search" id="findFriends" placeholder="search..." aria-label="Search" aria-describedby="search">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" name="search" type="submit">Search</button>
                            </div>
                        </div>
                    </form></li>
                <li class="nav-item"></li>
                <?php
                //Display log in button if not logged in
                if(!isset($_SESSION["login"])) {
                    echo '    
            
                        <li class="nav-item float-right"><a class="nav-link active" href="#" data-bs-toggle="modal" data-bs-target="#popUpLogin">Login</a></li>
                     <li class="nav-item float-right"><a href="index.php?register=true" class="nav-link active">Register</a></li>';
                }
                else {
                    //Display logout button if logged in
                    echo '
                        <li class="nav-item d-flex"><form method="post" action=""><button class="btn btn-light  my02 my-sm-0" 
                                    type="submit" name="logout" id="logoutButton" aria-label="Logout"> Logout</button> </form></li> ';
                }?>

            </ul>


        </div>
    </div>
</nav>


