<?php require_once 'template/header.phtml'?>
<nav class="navbar navbar-light bg-light">
    <a href="index.php"><img class="navbar-left" src="images/logo.transparent.gif" id="Logo" height="50vn" alt="logo" ></a>
    <form class="form-inline" action="search.php" method="post">
        <label for="findFriend">Find friends:&nbsp; </label>
        <input class="form-control mr-sm-2" name="searchField" type="search" id="findFriends" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" name="search" type="submit">Search</button>
    </form>
    <ul class="nav navbar-nav navbar-right d-inline-block">
        <li class="d-inline-block"><a href="selfAssesment.docx"><button class="btn btn-success my-2 my-sm-0 "
                                                                        type="button" id="assesmentButton"  aria-label="Login">Self-assesment</button></a></li>
        <?php
        //Display log in button if not logged in
        if(!isset($_SESSION["login"])) {
            echo '    
            
                        <li class="d-inline-block"><button class="btn btn-success my-2 my-sm-0 " 
                                    type="button"  data-bs-toggle="modal" data-bs-target="#exampleModal"  aria-label="Login">Login</button></li>
                     <li class="d-inline-block"><a href="registration.php"><button class="btn btn-success my-2 my-sm-0 " type="button" id="registrationButton"  aria-label="Registration">Register</button></a></li>';
        }
        else {
            //Display logout button if logged in
            echo '
                        <li class="d-inline-block"><form method="post" action=""><button class="btn btn-success my02 my-sm-0" 
                                    type="submit" name="logout" id="logoutButton" aria-label="Logout"> Logout</button> </form></li> ';
        }?>


        <!-- Button trigger modal -->
        <li><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Launch demo modal
        </button></li>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>


    </ul>
</nav>


