<!--Pagination-->
<nav class="mw-100" aria-label="pagination">
    <ul class="pagination flex-wrap">
        <?php
        if($_GET['page'] == 1) {
            echo '<li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a></li>';
        }else{
            $previousPage = $_GET['page'] - 1;
            echo '<li class="page-item"><a class="page-link" href="index.php?showAll=true&page='.$previousPage.'">Previous</a></li>';
        }
        for($page = 1 ; $page <= $view->numberOfPages; $page++) {
            if($page == $_GET['page']){
                echo'<li class="page-item active" aria-current="page"><a class="page-link" href="index.php?showAll=true&page='.$page.'">'.$page.'</a>';
            }else{
                echo '<li class="page-item"><a class="page-link" href="index.php?showAll=true&page='.$page.'">'.$page.'</a></li>';
            }

        }
        if($_GET['page'] == $view->numberOfPages) {
            echo '<li class="page-item disabled">
                            <a class="page-link" href="#">Next</a></li>';
        }else{
            $previousPage = $_GET['page'] + 1;
            echo '<li class="page-item"><a class="page-link" href="index.php?showAll=true&page='.$previousPage.'">Next</a></li>';
        }?>
    </ul>
</nav>