<?php require('template/header.phtml') ?>

<div class="col-xl-3 col-lg-3 col-md-2 col-sm-1 mx-auto"></div>
<div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 formBox mx-auto" id="registrationForm">
    <!--login form start-->
    <h3> Create a new Account </h3>
    <form class="px-3" action=""  method="post">
        <div class="form-group">
            <label for="nameInput">Name</label>
            <input type="text" class="form-control" name="firstName" id="nameInput" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="lastNameInput">Surname</label>
            <input type="text" class="form-control" name="lastName" id="lastNameInput" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="emailInput">E-mail address</label>
            <input type="email" class="form-control" name="email" id="emailInput" placeholder="E-mail address">
        </div>
        <div class="form-group">
            <label for="emailInput">Phone Number</label>
            <input type="text" class="form-control" name="phoneNo" id="phoneInput" placeholder="Phone">
        </div>
        <div class="form-group">
            <label for="emailInput">Username</label>
            <input type="text" class="form-control" name="uname" id="usernameInput" placeholder="Username">
        </div>
        <div class="form-group">
            <label for="passwordInput">Password</label>
            <input type="password" class="form-control" name="pwd" id="passwordInput" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="passwordRepeatInput">Re-type your password</label>
            <input type="password" class="form-control" name="pwdR" id="passwordRepeatInput" placeholder="Password">
        </div><!--
        <div class="form-group">
            <label for="addPhotoButton">Add profile image(optional)</label>
            <input type="file" class="form-control-file" id="addPhotoButton">
        </div>-->
        <button type="submit" name="register" class="btn btn-primary">Create Account</button>
    </form>
    <!--login form end-->
</div>

<?php require('template/footer.phtml');?>
