<?php require('template/header.phtml') ?>
<div class="row no-gutters">
     <div class="col-lg-5 col-md-5 col-sm-5 col-xs-0 messengerPanel" >
         <div class="row no-gutters">User profile and settings</div>
         <div class="row no-gutters">
             <div class="row input-group no-gutters" id="friendSearchWindow">
                 <div class="input-group-append">
                     <span class="btn btn-primary" type="submit" id="searchFriendsButton">Find</span>
                 </div>
                 <input type="text" class="form-control" placeholder="Search friends" id="friendsSearch">
             </div>
         </div>
         <div class="row no-gutters">Friends list</div>
     </div>
     <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 messengerPanel px-0">
         <div class="row no no-gutters">Chatee panel</div>
         <div class="row input-group no-gutters" id="messageSearchWindow">
             <div class="input-group-append">
                 <span class="btn btn-primary" type="submit" id="searchMessageButton">Find</span>
             </div>
             <input type="text" class="form-control" placeholder="Search messages" id="messageSearch">
         </div>
         <div class="row no-gutters" id="messageWindow">MESSAGES</div>
         <div class="row input-group no-gutters" id="inputWindow">
             <input type="text" class="form-control" placeholder="Type your message here" id="message">
             <div class="input-group-append">
                 <span class="btn btn-primary" type="submit" id="sendMessageButton">Send</span>
             </div>
         </div>
     </div>
 </div>

<?php require('template/footer.phtml') ?>
