<?php require('template/header.phtml') ?>

<div class="col-xl-3 col-lg-3 col-md-2 col-sm-1 mx-auto"></div>
<div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 formBox mx-auto">
    <!--login form start-->
    <h3> Reset your password </h3>
    <form class="p-3">
        <p>To reset your password, please enter your COMPANY NAME username. </p>
        <p>COMPANY NAME will send the password reset instructions to the email address for this account.</p>
        <div class="form-group">
            <label for="emailInput">Email Address:</label>
            <input type="email" class="form-control" id="emailInput" placeholder="E-mail">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <hr />
        Already have an account?
        <a href="index.php" role="button" class="btn btn-link" >Log in</a>
    </form>
    <!--login form end-->
</div>

<?php require('template/footer.phtml') ?>
