  <div class="footer">
      <p>Profile photos generated using Academic Dataset by Generated Photos. </p>
  </div>


  <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="js/jquery-3.6.0.min.js" type="text/javascript"></script>
  <!-- BootStrap JS -->
  <script src="js/bootstrap.bundle.js" type="text/javascript"></script>

  </body>
</html>