
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Client Server Systems assignment website">
    <meta name="author" content="Michal Brenda @00559233">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">


    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<!-- Main content starts here -->
<div class="container-fluid no-gutters p-0" id="content">








