<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Client Server Systems assignment website">
    <meta name="author" content="Michal Brenda @00559233">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">
    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">
<script>

    //Removes all child nodes of a given html item
    function removeAllChildNodes(parent) {
        while (parent.firstChild) {
            parent.removeChild(parent.firstChild);
        }
    }

    /**
     * Retrieves json file from the URL. Use in this manner: getJson(address, function(data) { do something here with the data })
     * @param url
     * @param callback a method that operates on returned data
     */
    function getJson(url, callback) {
        var request = new XMLHttpRequest();

        request.open('GET', url, true);

        request.onload = function() {
            if (request.status >= 200 && request.status < 400) {
                var json = JSON.parse(request.responseText);

                callback(json);

            } else {
                // server error
                console.error("There was a problem with connection. Error number: " + request.status);
                return;
            }
        };
        request.onerror = function() {
            console.error( "Can't connect to the server." );
            return;
        };
        request.send();
    }


    /**
     * Retrieves user's location and updates it in the database as well as in the script
     * Global variables userLat and userLon declared in the script in map.phtml
     */
    var userLon = 0;
    var userLat = 0;
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(position => {
                userLat += position.coords.latitude;
                userLon += position.coords.longitude;});
                // console.log('lon: ' + userLon + 'lat' + userLat);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }

</script>

<!-- Main content starts here -->
<div class="container-fluid no-gutters p-0" id="content">








